name: Deploy to VPS 🚀

on:
  push:
    branches:
      - main # Jalankan workflow hanya jika ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengambil kode dari repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Login ke VPS via SSH dan jalankan perintah deploy
          - name: Deploy to VPS
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USER }}
              key: ${{ secrets.VPS_SSH_KEY }}
              script: |
                # Masuk ke direktori aplikasi
                cd ~/app

                # Tarik kode terbaru
                git pull origin main

                # Bangun (build) Docker image baru dengan tag 'my-fastapi-app'
                docker build -t my-fastapi-app .

                # Hentikan container lama jika ada (abaikan error jika tidak ada)
                docker stop web-app || true

                # Hapus container lama jika ada (abaikan error jika tidak ada)
                docker rm web-app || true

                # Jalankan container baru dari image yang baru dibuat
                # -d: detached mode (jalan di background)
                # --name: beri nama container agar mudah dikelola
                # -p 8000:8000: mapping port 8000 di VPS ke port 8000 di container
                docker run -d --name web-app -p 8000:8000 my-fastapi-app