name: Deploy to VPS with Docker 🐳

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          
          script: |
            cd /root/app/fastapicicd

            git pull origin main

            sudo docker build -t my-fastapi-app .

            sudo docker stop web-app || true

            sudo docker rm web-app || true

            sudo docker run -d --name web-app -p 8000:8000 my-fastapi-app