name: Deploy to VPS 🚀

on:
  push:
    branches:
      - main # Jalankan workflow hanya jika ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengambil kode dari repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Login ke VPS via SSH dan jalankan perintah deploy
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}       # IP VPS dari secrets
          username: ${{ secrets.VPS_USER }}   # Username dari secrets
          key: ${{ secrets.VPS_SSH_KEY }}     # Kunci SSH privat dari secrets
          script: |
            # Masuk ke direktori aplikasi di VPS
            cd ~/app

            # Jika repository sudah ada, tarik perubahan terbaru. Jika belum, clone.
            if [ -d .git ]; then
              git pull origin main
            else
              git clone git@github.com:YourUsername/YourRepo.git .
            fi

            # Install/update dependensi Python
            pip3 install -r requirements.txt

            # Matikan proses uvicorn yang sedang berjalan (jika ada)
            # Cara sederhana, untuk produksi disarankan pakai systemd
            pkill uvicorn || true

            # Jalankan aplikasi di background
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &