# Nama workflow yang akan muncul di tab Actions GitHub
name: Deploy to VPS with Docker 🐳

# Pemicu (trigger) workflow
on:
  # Jalankan workflow setiap kali ada 'push' ke branch 'main'
  push:
    branches:
      - main

# Daftar pekerjaan (jobs) yang akan dijalankan
jobs:
  # Kita definisikan satu job bernama 'deploy'
  deploy:
    # Job ini akan berjalan di environment Ubuntu terbaru yang disediakan GitHub
    runs-on: ubuntu-latest

    # Langkah-langkah (steps) yang akan dieksekusi dalam job 'deploy'
    steps:
      # Langkah 1: Checkout kode
      # Step ini mengunduh kodemu ke dalam runner GitHub Actions
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Deploy ke VPS menggunakan SSH
      # Step ini menggunakan Action 'ssh-action' untuk login dan menjalankan perintah di VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # Ambil data sensitif dari GitHub Secrets
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          
          # Skrip yang akan dijalankan di dalam VPS
          script: |
            # Masuk ke direktori aplikasi yangbenar
            cd /root/app/fastapicicd

            # Tarik kode terbaru dari branch main
            git pull origin main

            # Bangun (build) Docker image baru dengan tag 'my-fastapi-app'
            # Titik (.) berarti Dockerfile ada di direktori saat ini
            sudo docker build -t my-fastapi-app .

            # Hentikan container lama jika ada (abaikan error jika tidak ada)
            sudo docker stop web-app || true

            # Hapus container lama jika ada (abaikan error jika tidak ada)
            sudo docker rm web-app || true

            sudo docker run -d --name web-app -p 8000:8000 my-fastapi-app
            # Jalankan container baru dari image yang baru dibuat
            # -d: detached mode (jalan di background)
            # --name: beri